name: Deploy to Replit on Push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Test build
      run: npm run build:web
      
    - name: Test server
      run: |
        timeout 10s node server.js &
        sleep 5
        curl -f http://localhost:5000/health || exit 1
        
    - name: ✅ Build Success
      run: echo "✅ Build e servidor testados com sucesso! Pronto para Replit."
